version: "3.9"

services:
  app:
    build: .
    container_name: flask-todo
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=production
      # send logs using path-based partition to VictoriaLogs (0/0 default)
      - VICTORIA_ACCOUNT_ID=0
      - VICTORIA_PROJECT_ID=0
    logging:
      driver: "json-file"
    depends_on:
      - prometheus
      - victorialogs
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    ports:
      - "9428:9428"  # Both query and ingestion share the same port
    command:
      - "-storageDataPath=/vmlogs"
      - "-retentionPeriod=7d"
      - "-httpListenAddr=:9428"
    volumes:
      - ./vmlogs-data:/vmlogs
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=myuser
      - GF_SECURITY_ADMIN_PASSWORD=mypassword
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - victorialogs
    restart: always

volumes:
  grafana-storage:
  vmlogs-data:
