[sources.docker_logs]
type = "docker_logs"
include_containers = ["flask-todo"]

[transforms.json_parse]
type = "remap"
inputs = ["docker_logs"]
source = '''
. |= parse_json!(.message) ?? {"raw": .message}
'''

[sinks.vm_logs]
type = "http"
inputs = ["json_parse"]
uri = "http://victorialogs:9424/insert/jsonline"
encoding.codec = "json"
compression = "none"
